apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"    
  name: {{ .Values.cluster.name }}
  namespace: hcp-config
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: 2
  management:
    autoRepair: false
    upgradeType: InPlace
  platform:
    type: Agent
    agent:
      agentLabelSelector:
        matchExpressions:
        - {key: 'agentclusterinstalls.extensions.hive.openshift.io/location', operator: In, values: [{{ .Values.cluster.name }}]}      
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.13.40-multi
