apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .Values.cluster.name }}
  annotations:  
    import.open-cluster-management.io/hosting-cluster-name: local-cluster
    import.open-cluster-management.io/klusterlet-deploy-mode: Hosted
    open-cluster-management/created-via: hypershift  
  labels:
    cloud: BareMetal
    name: {{ .Values.cluster.name }}
    vendor: OpenShift
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
  taints:
    - effect: NoSelect
      key: cluster.open-cluster-management.io/unreachable
