apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: {{ .Values.cluster.name }}
  namespace: hcp-config
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: 2
  management:
    autoRepair: false
    upgradeType: InPlace
  platform:
    type: Agent
    agent:
      agentLabelSelector:
        matchLabels: 
          agentclusterinstalls.extensions.hive.openshift.io/location: {{ .Values.cluster.name }}       
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.13.40-multi
