apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcp02-creation
  namespace: openshift-gitops
spec:
  destination:
    namespace: hpc-config
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: cluster.name
          value: hcp02
    path: chart
    repoURL: 'https://github.com/fdavalo/hcp-agent.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true      
